keys:
  - &admin age1m5ahd365rg3tvdf7ewrnd0a7d4p75sjsentnz63cw8kfrekvg5pq7cmmdf
  - &kelpy age1s22m75z2ppv03aa223duv8wnfltvfm7r2rjfmglwv067v23ukdmsh2956a
  - &stargazer age1yypsg756str7zgpctxwtrrrlmlkfrh6l2nsaxl209n6xng5rl5dq54fdf0
  - &porcupineFish age1aq4fp9qrhz03vqrzj8gjw4xm2dgkueudflzex8vmmrg8efe0rswqcv8jah
creation_rules:
  - path_regex: users/inkpotmonkey/secrets.yaml$
    key_groups:
      - age:
          - *admin
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin
          - *kelpy
          - *stargazer
          - *porcupineFish
