keys:
  - &admin age1m5ahd365rg3tvdf7ewrnd0a7d4p75sjsentnz63cw8kfrekvg5pq7cmmdf
  - &kelpy age1dkaspaaf6edwzn9wqg9dfjacna3zqkg8rwzstuegqvnjma9fmdqqz0380g
  - &porcupineFish age1g8sd9yd7emzyq5r8uuxyc30mtntmc7n46exuhdjl7g83hl2az56s8cwcvf
creation_rules:
  - path_regex: users/inkpotmonkey/secrets.yaml$
    key_groups:
      - age:
          - *admin
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin
          - *kelpy
          - *porcupineFish
