{
  pkgs,
  config,
  lib,
  self,
  ...
}:

{
  options.custom.home.profiles.emacs = {
    enable = lib.mkEnableOption "Emacs configuration (pgtk, tree-sitter, doom-inspired)";
  };

  config = lib.mkIf config.custom.home.profiles.emacs.enable {

    programs.emacs = {
      enable = true;
      package = pkgs.emacsWithPackagesFromUsePackage {
        config = builtins.readFile ./init.el;
        package = pkgs.emacs-pgtk;
        alwaysEnsure = true;
        override =
          epkgs:
          epkgs
          // (import ./packages.nix { inherit epkgs pkgs; })
          // {
            "shell-command+" = epkgs.shell-command-plus;
          };
        extraEmacsPackages = epkgs: [
          epkgs.just-mode
          epkgs.just-ts-mode
          epkgs.justl
          epkgs.treesit-grammars.with-all-grammars

          # MCP server for agentic Elisp development — describes functions,
          # reads source files, looks up Info docs, etc.
          epkgs.elisp-dev-mcp
          epkgs.mcp-server-lib
        ];
      };
    };

    services.emacs = {
      enable = true;
      package = config.programs.emacs.finalPackage;
      startWithUserSession = false; # Don't start at login
      socketActivation.enable = true; # Wait for client connection
    };

    # Emacs configuration
    xdg.configFile = {
      # init.el ships verbatim — it carries safe fallbacks for every site fact
      # and `(load "my-site-config")` at startup. Host/user-specific values are
      # injected out-of-band via the generated module below, so init.el needs no
      # string substitution and stays loadable/testable outside Nix.
      "emacs/init.el" = {
        source = ./init.el;
      };
      # The Nix seam: this generated Elisp overrides the `my-site/*` fallbacks in
      # init.el with the real identity/secret/grammar paths. init.el loads it.
      "emacs/my-site-config.el" = {
        text = ''
          ;;; my-site-config.el --- Nix-generated site facts -*- lexical-binding: t -*-
          ;;; Commentary:
          ;;; Generated by home-manager (users/inkpotmonkey/home/emacs/default.nix).
          ;;; Overrides the `my-site/*' fallbacks declared in init.el.
          ;;; Code:
          (setq my-site/username "${config.identity.username}")
          (setq my-site/email "${config.identity.email}")
          (setq my-site/secrets-file "${self.lib.getSecretPath "users/inkpotmonkey.yaml"}")
          (setq my-site/treesit-load-path "${pkgs.emacsPackages.treesit-grammars.with-all-grammars}/lib")
          (provide 'my-site-config)
          ;;; my-site-config.el ends here
        '';
      };
      "emacs/early-init.el" = {
        source = ./early-init.el;
      };
    };

    services.gpg-agent = {
      pinentry.package = config.programs.emacs.finalPackage;
      extraConfig = ''
        allow-emacs-pinentry
        allow-loopback-pinentry
      '';
    };

    # Emacs-specific tools that are not general dev tools live here; all LSPs and
    # general dev tools are in dev.nix, so this stays empty for now.
    home.packages = [ ];

    programs.info.enable = true;
  };
}
