{ pkgs, ... }:

pkgs.testers.nixosTest {
  name = "git-annex-sync";
  nodes = {
    gateway = { config, pkgs, ... }: {
      imports = [ ../default.nix ];
      services.git-annex = {
        enable = true;
        repositories.gateway = {
          path = "/var/lib/git-annex/gateway";
          description = "gateway";
          gateway = true;
          assistant = true;
          wanted = "standard";
          group = "transfer";
        };
      };
      networking.firewall.allowedTCPPorts = [ 22 ];
      services.openssh.enable = true;
    };

    client = { config, pkgs, ... }: {
      imports = [ ../default.nix ];
      services.git-annex = {
        enable = true;
        repositories.client = {
          path = "/var/lib/git-annex/client";
          description = "client";
          assistant = true;
          remotes = [{
            name = "origin";
            url = "git-annex@gateway:/var/lib/git-annex/gateway";
          }];
        };
      };
    };
  };

  testScript = ''
    start_all()
    
    # Wait for SSH
    gateway.wait_for_unit("sshd")
    
    # Get gateway's public key (generated by module)
    gateway.wait_for_file("/var/lib/git-annex/.ssh/id_ed25519.pub")
    key = gateway.succeed("cat /var/lib/git-annex/.ssh/id_ed25519.pub")
    
    # Get client's public key
    client.wait_for_file("/var/lib/git-annex/.ssh/id_ed25519.pub")
    client_key = client.succeed("cat /var/lib/git-annex/.ssh/id_ed25519.pub")
    
    # Authorize client on gateway
    gateway.succeed(f"mkdir -p /var/lib/git-annex/.ssh && echo '{client_key}' >> /var/lib/git-annex/.ssh/authorized_keys && chown git-annex:git-annex /var/lib/git-annex/.ssh/authorized_keys")
    
    # Configure client to accept gateway host key (disable strict checking for test)
    client.succeed("mkdir -p /var/lib/git-annex/.ssh && echo 'Host *\n  StrictHostKeyChecking no\n' > /var/lib/git-annex/.ssh/config && chown git-annex:git-annex /var/lib/git-annex/.ssh/config")
    
    # Create file on client
    client.succeed("sudo -u git-annex bash -c 'cd /var/lib/git-annex/client && echo test > test.txt'")
    
    # Check environment
    client.succeed("ls -l /run/current-system/sw/bin/git")
    client.succeed("which git")

    # Force sync manually to debug connectivity
    code, stdout = client.execute("sudo -u git-annex /run/current-system/sw/bin/git -C /var/lib/git-annex/client annex sync 2>&1")
    print(stdout)
    if code != 0:
      raise Exception(f"Sync failed: {stdout}")
    
    # Wait for sync
    gateway.wait_for_file("/var/lib/git-annex/gateway/test.txt")
  '';
}
