#+TITLE: THE EMACSULARITY
#+DESCRIPTION: An exploration of the inevitable Emacsularity
#+PROPERTY: header-args :results silent
#+STARTUP: content

All consuming, universe engulfing the Emacsularity draws nigh, Cthulhu stumbles as the parenthetical weight draws him ever further into a config of his own making.

Here lies the record of my dance through the belly of the beast, it will change as I continue to explore the dark reaches of this ever shifting land that beckons me deeper into its all consuming grasp.

These words are a record of my dalliance with the dream of truly calling an editor my own. As I change so shall it, this is the only way it could ever truly be.

* EARLY INIT
:PROPERTIES:
:header-args:emacs-lisp: :tangle ./early-init.el
:END:

The [[info:emacs#Early Init File][early init file]] deals with customizations that need to happen really early in the startup process. Most notably in this case what we are doing here is disabling *all* of the in built Emacs package management and activating all packages that Nix has installed during the build process. What activating means here is a activity that is left up to the reader to discover (I am that reader).

Henrik in Doom Emacs's [[https://github.com/doomemacs/doomemacs/blob/master/early-init.el][early-init.el]] also adds a bunch of startup optimisations that feel out of place in my little corner of the Emacsularity.

#+begin_src emacs-lisp
;;; early-init.el --- Early Init File -*- lexical-binding: t; no-byte-compile: t -*-

(custom-set-variables
 ;; Disable startup screen
 '(inhibit-startup-screen t)
 '(inhibit-startup-message t)
 '(inhibit-startup-echo-area-message t)
 '(initial-scratch-message nil)

 ;; Frame settings
 '(initial-frame-alist '((left-fringe . 0)
			 (right-fringe . 0)
			 (internal-border-width . 8)
			 (tool-bar-lines . 0)))

 ;; Disable UI elements aka
 ;; remove all indications that this is usable to the uniniated!
 '(menu-bar-mode nil)
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil)

 ;; Buffer settings
 '(initial-buffer-choice t)

 ;; Frame behavior
 '(frame-inhibit-implied-resize t)
 '(frame-title-format nil)

 ;; Using use-package :vc for all packages
 '(package-enable-at-startup nil))

;; For Emacs v29
(add-to-list 'default-frame-alist '(undecorated . t))
(add-to-list 'initial-frame-alist '(fullscreen . maximized))

(add-hook 'window-setup-hook #'toggle-frame-fullscreen)

;; no-littering
;; Stop the littering of the native compile cache
(when (and (fboundp 'startup-redirect-eln-cache)
           (fboundp 'native-comp-available-p)
           (native-comp-available-p))
  (startup-redirect-eln-cache
   (convert-standard-filename
    (expand-file-name  "var/eln-cache/" user-emacs-directory))))

;;; early-init.el ends here
#+end_src

* INIT
:PROPERTIES:
:header-args:emacs-lisp: :tangle ./init.el
:END:

#+begin_src emacs-lisp
;;; init.el --- Init File -*- lexical-binding: t -*-
#+end_src

I set up everything with use-package even [[https://edoput.it/2022/07/19/use-package.html][builtin emacs packages]].

Custom functions always have the suffix ~+~ to distinguish them and allow easy searching via regex.

** EDITOR

*** USE PACKAGE

I use this macro to configure everything as it gives simulacrum of control to what can be the chaotic experience of configuring Emacs

#+begin_src emacs-lisp
(custom-set-variables
  '(use-package-always-ensure t)
  '(package-archives nil)
  '(use-package-always-demand t))
#+END_src

*** NO LITTERING
Similar to XDG home being polluted by lots of packages this fixes this issue for Emacs

[[https://github.com/emacscollective/no-littering?tab=readme-ov-file#usage][NOTE: This needs to be loaded as early as possible]]

#+begin_src emacs-lisp
(use-package no-littering
    :vc (:url "https://github.com/emacscollective/no-littering"
              :rev :newest)
    :config
    ;; Set for customisations though I never use them
    (setq custom-file (no-littering-expand-etc-file-name "custom.el"))
    ;; Setup for backup files as well hopefully the precautions taken below
    ;; address the concerns in the function documentation.
    (no-littering-theme-backups)

    ;; enable for recent files
    (require 'recentf)
    (add-to-list 'recentf-exclude
                 (recentf-expand-file-name no-littering-var-directory))
    (add-to-list 'recentf-exclude
                 (recentf-expand-file-name no-littering-etc-directory)))
#+end_src

*** GENERAL SETTINGS

#+begin_src emacs-lisp
(use-package emacs
  :custom
  (user-full-name "@username@")
  (user-mail-address "@email@")
  (confirm-kill-emacs 'yes-or-no-p)

  (set-default-coding-systems 'utf-8)
  
  ;; Single space denotes the end of a sentence not double
  (sentence-end-double-space nil)

  ;; I dont want emacs to make a noise on every mistake but
  ;; some sort of feedback would be appreciated. This is an
  ;; experiment in progress
  ;; https://www.emacswiki.org/emacs/AlarmBell
  (visible-bell t)
  
  ;; I want dialogs to be confirmed via the echo area y-n
  (use-file-dialog nil)
  
  (frame-resize-pixelwise t)

  ;; Yes I would like a list of my recent files please
  (recentf-mode t)
  
  ;; As no one else's uses my computer this should be fine...
  (password-cache-expiry nil)

  ;; Show me visually whether the space is over a tab or a spce
  (x-stretch-cursor t)
  
  ;; always allow 'y' instead of 'yes'.
  (use-short-answers t)
  
  ;; follow symlinks
  (vc-follow-symlinks t)
  
  ;; Show column number in mode line
  (column-number-mode t)

  ;; Revert buffers when the underlying file has changed
  ;; Not sure about this one
  (global-auto-revert-mode t)
  ;; Revert Dired and other buffers
  ;; Reverting = Refreshing
  (global-auto-revert-non-file-buffers t)
  
  ;; Typed text replaces the selection if the selection is active,
  ;; pressing delete or backspace deletes the selection.
  ;; write over selected text on input... like all modern editors do
  (delete-selection-mode t)
  
  ;; Do not save duplicates in kill-ring
  (kill-do-not-save-duplicates t)
  
  ;; scrolling
  (scroll-margin 2)
  (scroll-preserve-screen-position t)
  (fast-but-imprecise-scrolling t)
  (auto-window-vscroll nil)
  (scroll-conservatively 101)
  ;; Yes to smooooooth scrolling
  (pixel-scroll-precision-mode t)
  
  ;; Assume everything is left to right as that is all I interact with
  (bidi-paragraph-direction 'left-to-right)
  (bidi-inhibit-bpa t)
  
  ;; Better support for files with long lines
  (global-so-long-mode t)
  
  ;; Enable savehist-mode for command history
  (savehist-mode t)

  ;; Hide commands in M-x which do not apply to the current mode.
  (read-extended-command-predicate #'command-completion-default-include-p)

  ;; Enable indentation+completion using the TAB key.
  (tab-always-indent 'complete)

  :config
  ;; Need to be aware that some major modes do this in the background, emacs-lisp for example adds ("lambda" . "λ")
  (global-prettify-symbols-mode t)

  (abbrev-mode)
  
  ;; https://emacs.stackexchange.com/questions/249/how-to-search-and-replace-in-the-entire-buffer
  (defun goto-top-if-no-region+ (orig-func &rest args)
    "if region is not active, go to the buffer start"
    (save-excursion
      (when (not (use-region-p))
        (goto-char (point-min)))
      (apply orig-func args)))

  (advice-add 'query-replace :around #'goto-top-if-no-region+)
  (advice-add 'query-replace-regexp :around #'goto-top-if-no-region+)

  :bind
  ;; I prefer this less destructive way of thinking
  ("M-z" . zap-up-to-char)
  
  ;; I use regex a lot more than not
  ("M-%" . query-replace-regexp))
#+end_src

*** CRUX
[[https://github.com/bbatsov/crux][A Collection of Ridiculously Useful eXtensions for Emacs]]

This package lives up to its name! Though better keybinding is in order. Especially as I use ~crux-top-join-line~ all the time...

#+begin_src emacs-lisp
(use-package crux
    :vc (:url "https://github.com/bbatsov/crux"
              :rev :newest)
    :bind
    ("C-k" . crux-smart-kill-line)
    ("C-a" . crux-move-beginning-of-line)
    ("s-j" . crux-top-join-line)
    ("C-c e" . crux-eval-and-replace)
    ("C-<return>" . crux-smart-open-line-above)
    ("M-o" . crux-other-window-or-switch-buffer)
    ("C-c r" . crux-rename-file-and-buffer)
    ("C-g" . crux-keyboard-quit-dwim)
    :config
    (crux-with-region-or-buffer indent-region)
    (crux-with-region-or-buffer untabify))
#+end_src

*** WINDOWS OF THE SOUL

Managing windows is a constant task, here gathers the dust of my Sisyphean toil to make it more manageable.

#+begin_src emacs-lisp
(use-package emacs
  :custom
  ;; enable winner mode globally for undo/redo window layout changes
  (winner-mode t)
  
  ;; Be fair when stealing screen size from other windows
  (window-combination-resize t))
#+end_src

**** ACE WINDOWS
#+begin_src emacs-lisp
(use-package ace-window
  :vc (:url "https://github.com/abo-abo/ace-window" :rev :newest)
  :bind ("M-o" . ace-window)
  :custom
  (aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
  :config
  (ace-window-display-mode 1))
#+end_src

*** FRAMES

[[https://github.com/tumashu/posframe][tumashu/posframe: Pop a posframe (just a child-frame) at point, posframe is a **GNU ELPA** package!]]

Baby frames used my various down stream packages

#+begin_src emacs-lisp
(use-package posframe
        :vc (:url "https://github.com/tumashu/posframe"
              :rev :newest))
#+end_src

*** KILLING AKA CUT

**** PULSING

#+begin_src emacs-lisp
(use-package goggles
    :vc (:url "https://github.com/minad/goggles" :rev :newest)
  :hook ((prog-mode text-mode) . goggles-mode)
  :config
  (setq-default goggles-pulse t))
#+end_src

**** SYSTEM CLIPBOARD

At some point I want Emacs to function as a clipboard manager, which due to the architectural decisions of Wayland is a bit harder to achieve [[https://whynothugo.nl/journal/2022/10/21/how-the-clipboard-works/][how the clipboard works]]. I /could/ install a clipboard manager as suggested at the bottom of the [[https://www.emacswiki.org/emacs/CopyAndPaste][wiki]] but this feels like overkill.

This seems possible to do with wl-clipboard but requires that the Wayland compositor implements the [[https://wayland.app/protocols/wlr-data-control-unstable-v1][wlr data control protocol]]. The only Compositors that support this at the moment <2024-03-21 Thu> are KWin, Sway and Hyprland so this is on the wish list until I make the leap to one of those.

Until then this is a litter nicety
#+begin_src emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+end_src

*** HANDLE ENV VARS

[[https://github.com/purcell/exec-path-from-shell][A GNU Emacs library to ensure environment variables inside Emacs look the same as in the user's shell]]

#+begin_src emacs-lisp
(use-package exec-path-from-shell
    :vc (:url "https://github.com/purcell/exec-path-from-shell"
              :rev :newest)
  :config
  (dolist (var '("SSH_AUTH_SOCK" "SSH_AGENT_PID" "NIX_PATH"))
    (add-to-list 'exec-path-from-shell-variables var))
  (exec-path-from-shell-initialize)

  (when (daemonp)
    (exec-path-from-shell-initialize)))
#+end_src

*** AUTO SAVING & BACKUPS

[[https://github.com/bbatsov/super-save][super-save auto-saves your buffers, when certain events happen - e.g. you switch between buffers, an Emacs frame loses focus, etc.]]

#+begin_src elisp
;; Backup settings
(use-package emacs
  :custom
  ;; Backup settings
  (make-backup-files t)
  (backup-by-copying t)
  (version-control t)
  (delete-old-versions t)
  (delete-by-moving-to-trash t)
  (kept-old-versions 6)
  (kept-new-versions 9)
  
  ;; Disable built-in auto-save (super-save will handle this)
  (auto-save-default nil)
  
  ;; No lock files
  (create-lockfiles nil))

;; Super-save for intelligent auto-saving
(use-package super-save
  :vc (:url "https://github.com/bbatsov/super-save" :rev :newest)
  :custom
  (super-save-auto-save-when-idle t)
  (super-save-idle-duration 20)  ;; Using your preferred 20s timeout
  (super-save-exclude '("^secrets.*"))
  (super-save-remote-files nil)
  (super-save-max-buffer-size 1000000)  ;; ~1MB limit
  (super-save-silent t)
  :config
  (super-save-mode +1))
#+end_src

*** REPEAT
[[https://karthinks.com/software/it-bears-repeating/][It Bears Repeating: Emacs 28 & Repeat Mode | Karthinks]]
#+begin_src emacs-lisp
(use-package emacs
    :config
  (repeat-mode))
#+end_src

*** UNDO
This is a surprisingly complicated endeavour

First lets set some modern limits
#+begin_src emacs-lisp
(setq undo-limit 67108864) ; 64mb.
(setq undo-strong-limit 100663296) ; 96mb.
(setq undo-outer-limit 1006632960) ; 960mb.
#+end_src

**** UNDO FU
[[https://github.com/emacsmirror/undo-fu][GitHub - emacsmirror/undo-fu: Undo helper with redo]]
#+begin_src emacs-lisp
(use-package undo-fu
    :vc (:url "https://github.com/emacsmirror/undo-fu" :rev :newest)
  :custom
  (undo-fu-session-compression 'zst)
  :bind
  ("C-z" . undo-fu-only-undo)
  ("C-S-z" . undo-fu-only-redo))
#+end_src

**** VUNDO
To visualise the path is to walk it
[[https://github.com/casouri/vundo][GitHub - casouri/vundo: Visualize the undo tree.]]
#+begin_src emacs-lisp
(use-package vundo
    :vc (:url "https://github.com/casouri/vundo" :rev :newest))
#+end_src

**** UNDO FU SESSION
Save undoings between starting and closing Emacs

#+begin_src emacs-lisp
(use-package undo-fu-session
    :vc (:url "https://github.com/emacsmirror/undo-fu-session" :rev :newest)
  :custom
  (undo-fu-session-incompatible-files '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
  :config
  (undo-fu-session-global-mode))
#+end_src

*** HELP
Some packages to improve the help of Emacs

**** INFO

Lets give our info buffers some sparkle
#+begin_src emacs-lisp
(use-package info-colors
    :vc (:url "https://github.com/ubolonton/info-colors" :rev :newest)
  :hook
  (Info-selection . info-colors-fontify-node))
#+end_src

Annoyingly the home-manager ~programs.info.enable = true~ directive does not work for me. Might be something to do with how I am using the emacs-overlay. Setting it manually for now.
#+begin_src emacs-lisp
(use-package info
  :disabled
  :no-require
  :config
  (add-to-list 'Info-directory-list "/nix/store/9kxbqh8mp3x1x2hmzzv4b5cvlmszlbap-emacs-packages-deps/share/emacs/site-lisp/elpa"))
#+end_src

**** WHICH KEY

Which key is an essential, a map to the dense forest of Emacs
#+begin_src emacs-lisp
(use-package which-key
  :config
  (which-key-mode))
#+end_src

**** HELPFUL

Provides a lot more contextual information 
#+begin_src emacs-lisp
(use-package helpful
    :vc (:url "https://github.com/Wilfred/helpful" :rev :newest)
    
  :bind
  ([remap describe-function] . helpful-callable)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . helpful-variable)
  ([remap describe-symbol] . helpful-symbol)
  ([remap describe-key] . helpful-key))
#+end_src

**** DEMOS 

Show me the code!
#+begin_src emacs-lisp
(use-package elisp-demos
    :vc (:url "https://github.com/xuchunyang/elisp-demos" :rev :newest)
  :after helpful
  :config
  (advice-add 'helpful-update
              :after #'elisp-demos-advice-helpful-update))
#+end_src

**** EROS

This prints the results of an emacs-lisp sexp
#+begin_src emacs-lisp
(use-package eros
    :vc (:url "https://github.com/xiongtx/eros" :rev :newest)
  :config
  (eros-mode 1))
#+end_src

*** WGREP
Grep is widely used this package makes its results actionable

#+begin_src emacs-lisp
(use-package wgrep
    :vc (:url "https://github.com/mhayashi1120/Emacs-wgrep" :rev :newest)
  :after embark

  :custom (wgrep-auto-save-buffer t)
  
  :bind
  (:map embark-collect-mode-map
        ("i" . wgrep-change-to-wgrep-mode))
  (:map wgrep-mode-map
        ("s-e" . wgrep-finish-edit)
        ("s-k" . wgrep-abort-changes)))
#+end_src

*** AUTH SOURCE SOPS

#+begin_src emacs-lisp
(use-package auth-source-sops
    :vc (:url "https://github.com/inkpot-monkey/auth-source-sops" :rev :newest)
    :custom
    ;; temp hardcoding for testing
    (auth-source-sops-file "/home/inkpotmonkey/.config/nixos/secrets/secrets.yaml")
    ;; (auth-source-sops-file "@sops-file@")
    :config
    (auth-source-sops-enable))
#+end_src

** UI
*** FONTS

I thought I would never leave source code pro behind but this beauty has captured my heart [[https://www.recursive.design/][Recursive Sans & Mono]].

#+begin_src emacs-lisp
(use-package fontaine
        :vc (:url "https://github.com/protesilaos/fontaine"
              :rev :newest)
  :custom
  (fontaine-presets 
   '((regular
      :default-family "Rec Mono Linear"
      :default-weight regular
      :default-height 80
      :variable-pitch-family "Recursive Sans Casual Static"
      )))
  
  :config
  ;; Recover last preset or fall back to desired style from
  (fontaine-set-preset (or (fontaine-restore-latest-preset) 'regular))

  (fontaine-mode 1))
#+end_src

*** EF THEMES

[[https://protesilaos.com/emacs/ef-themes][Ef (εὖ) themes for GNU Emacs | Protesilaos Stavrou]]

#+begin_src emacs-lisp
(use-package ef-themes
    :vc (:url "https://github.com/protesilaos/ef-themes" :rev :newest)
  :init
  ;; Mark all themes as safe, perhaps unsafe but whatcha goin to do
  (setq custom-safe-themes t)
  
  :custom
  (ef-themes-headings
   '((0 extrabold 1.5)
     (t variable-pitch 1.0)))

  (ef-themes-mixed-fonts t)
  (ef-themes-variable-pitch-ui t)
  (ef-themes-to-toggle '(ef-day ef-dream))

  :config
  ;; Load a theme at startup
  (ef-themes-select 'ef-dream))
#+end_src

*** SPACIOUS PADDING

#+begin_src emacs-lisp
(use-package spacious-padding
  :vc (:url "https://github.com/protesilaos/spacious-padding" :rev :newest)
  :custom

  (spacious-padding-subtle-frame-lines
   '(:mode-line-active default
     :mode-line-inactive vertical-border))

  (spacious-padding-widths
   '(:internal-border-width 15
     :header-line-width 4
     :mode-line-width 3
     :tab-width 4
     :right-divider-width 15
     :scroll-bar-width 8
     :fringe-width 8))

  (x-underline-at-descent-line t)
  :config
  (spacious-padding-mode))
#+end_src

*** VISUAL LINES
Emacs wraps lines when programming by their fill column but doesn't do it for visual lines which I dont like as it doesnt conform to the idea of an optimal line length [[https://baymard.com/blog/line-length-readability][Readability: The Optimal Line Length – Articles – Baymard Institute]]

[[https://codeberg.org/joostkremers/visual-fill-column][⛰ joostkremers/visual-fill-column]]

#+begin_src emacs-lisp
(use-package visual-fill-column
    :vc (:url "https://codeberg.org/joostkremers/visual-fill-column" :rev :newest)
    :custom
    (visual-fill-column-width 70)  ;; Explicitly set width
    (visual-fill-column-center-text t)
    (visual-fill-column-enable-sensible-window-split t)
    (visual-fill-column-adjust-for-text-scale t)  ;; Explicit is better

    :config
    (advice-add 'text-scale-adjust :after #'visual-fill-column-adjust))
#+end_src

*** FORM FEED
[[https://stackoverflow.com/questions/1576887/what-does-l-in-emacs-lisp-source-code-mean][ elisp - What does ^L in (Emacs Lisp) source code mean?]]

A pretty formatting of the form-feed character

#+begin_src emacs-lisp
(use-package form-feed
:vc (:url "https://depp.brause.cc/form-feed" :rev :newest)    
  :config
  (global-form-feed-mode))
#+end_src

*** (NERD) ICONS

#+begin_src emacs-lisp
(use-package nerd-icons
    :vc (:url "https://github.com/rainstormstudio/nerd-icons.el" :rev :newest)
  ;; :custom
  ;; The Nerd Font you want to use in GUI
  ;; "Symbols Nerd Font Mono" is the default and is recommended
  ;; but you can use any other Nerd Font if you want
  ;; (nerd-icons-font-family "Symbols Nerd Font Mono")
  )
#+end_src

*** RAINBOW DELIMITERS

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
        :vc (:url "https://github.com/Fanael/rainbow-delimiters" :rev :newest)
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

** DIRED

#+begin_src emacs-lisp
(use-package dired
  :custom
  ;; Copy across buffers
  (dired-dwim-target t)
  :bind
  (:map dired-mode-map
        ;; This replaces 'negative-argument
        ;; Which I have yet to use in this context
        ("-" . dired-up-directory))
    :hook (dired-mode . dired-hide-details-mode))
#+end_src

#+begin_src emacs-lisp
(use-package dired-git-info
    :vc (:url "https://github.com/clemera/dired-git-info" :rev :newest)    
    :bind (:map dired-mode-map
                (")" . dired-git-info-mode)))
#+end_src

#+begin_src emacs-lisp
(use-package diredfl
    :vc (:url "https://github.com/purcell/diredfl" :rev :newest)
  :config
  (diredfl-global-mode))
#+end_src

#+begin_src emacs-lisp
(use-package dired-x
    :custom (dired-auto-revert-buffer t)
  :hook (dired-mode . dired-omit-mode))
#+end_src

#+begin_src emacs-lisp
(use-package dired-subtree
:vc (:url "https://github.com/Fuco1/dired-hacks" :rev :newest)        
  :after dired
  :bind
  (:map dired-mode-map
    ("<tab>" . dired-subtree-toggle)
    ("TAB" . dired-subtree-toggle)
    ("<backtab>" . dired-subtree-remove)
    ("S-TAB" . dired-subtree-remove))
  :config
  (setq dired-subtree-use-backgrounds nil))
#+end_src

#+begin_src emacs-lisp
(use-package wdired
  :after dired
  :custom
  (wdired-allow-to-change-permissions t)
  (wdired-use-interactive-rename t)
  (wdired-confirm-overwrite t)
  (wdired-use-dired-vertical-movement 'sometimes)
  :bind
  (:map dired-mode-map
        ;; This replaces dired-maybe-insert-subdir
        ;; Which I never use and want to replace with
        ;; some sort of tree insertion in any case
        ("i" . dired-toggle-read-only))
  (:map wdired-mode-map
        ("s-q" . wdired-exit)))
#+end_src

#+begin_src emacs-lisp
(use-package nerd-icons-dired
    :vc (:url "https://github.com/rainstormstudio/nerd-icons-dired" :rev :newest)
    :after (nerd-icons dired)
      :hook
  (dired-mode . nerd-icons-dired-mode))
#+end_src

*** SIDEBAR

#+begin_src emacs-lisp
(use-package dired-sidebar
  :vc (:url "https://github.com/jojojames/dired-sidebar" :rev :newest)
  :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
  :ensure t
  :commands (dired-sidebar-toggle-sidebar)
  :custom
  (dired-sidebar-theme 'nerd)
  (dired-sidebar-use-term-integration t)
  (dired-sidebar-use-custom-font t))

(use-package ibuffer-sidebar
  :vc (:url "https://github.com/jojojames/ibuffer-sidebar" :rev :newest)
  :commands (ibuffer-sidebar-toggle-sidebar)
  :bind ("C-x C-p" . ibuffer-sidebar-toggle-sidebar))
#+end_src

** MOVEMENT
*** AVY

#+begin_src emacs-lisp
(use-package avy
    :vc (:url "https://github.com/abo-abo/avy" :rev :newest)
  :bind ("M-j" . avy-goto-char-timer)
  (:map goto-map ("l" . avy-goto-line))
  :custom
  (avy-timeout-seconds 0.2))
#+end_src

*** LINK HINT

I love this way of moving around. Just need to expand it to recognise relative file paths and paths inside of quotations.

For future work:
[[https://www.reddit.com/r/emacs/comments/uek8mt/integrating_embark_linkhint/][Integrating embark & link-hint]]

#+begin_src emacs-lisp
(use-package link-hint
    :vc (:url "https://github.com/noctuid/link-hint.el" :rev :newest)
  :bind ("M-J" . link-hint-open-link))
#+end_src

*** MOVE TEXT
[[https://github.com/emacsfodder/move-text][emacsfodder/move-text: move current line or region up or down]]

#+begin_src emacs-lisp
(use-package move-text
  :vc (:url "https://github.com/emacsfodder/move-text" :rev :newest)
  :config
  (move-text-default-bindings))
#+end_src

*** MARK

How I utilize the mark to jump around is in its infancy.

This allows for quick jumping back via ~C-u C-<space>~ and then following the only ~C-<space>~ is needed.

Questions
1. What is a good keybinding for going backwards and forwards on the mark ring?
2. Should I always use the global mark ring? This seems to be the behaviour that I want.

#+BEGIN_src emacs-lisp
(use-package emacs
  :custom
  (set-mark-command-repeat-pop t)

  :config
  (defun unpop-to-mark-command+ ()
    "Unpop off mark ring. Does nothing if mark ring is empty."
    (interactive)
    (when mark-ring
      (setq mark-ring (cons (copy-marker (mark-marker)) mark-ring))
      (set-marker (mark-marker) (car (last mark-ring)) (current-buffer))
      (when (null (mark t)) (ding))
      (setq mark-ring (nbutlast mark-ring))
      (goto-char (marker-position (car (last mark-ring)))))))
#+end_src

**** VISIBLE MARK
[[https://git.sr.ht/~iank/visible-mark/tree/master][~iank/visible-mark (master): / - sourcehut git]]
[[https://pragmaticemacs.wordpress.com/2015/06/22/regions-marks-and-visual-mark/][Regions, marks, and visible-mark | Pragmatic Emacs]]

This adds a nice _ to where the mark is in the file that is the same colour as the cursor.

#+begin_src emacs-lisp
(use-package visible-mark
    :vc (:url "https://github.com/emacsmirror/visible-mark" :rev :newest)
  :init
  (defface visible-mark-active
    `((((type tty) (class mono)))
      (t (:underline ,(face-attribute 'cursor :background))))
    "Active mark face."
    :group 'visible-mark)
  :custom
  (visible-mark-max 1)
  (visible-mark-faces '(visible-mark-active))
  :config
  (global-visible-mark-mode +1))
#+end_src

** COMPLETION

*** ORDERLESS
Improve selecting completions
#+begin_src emacs-lisp
(use-package orderless
    :vc (:url "https://github.com/oantolin/orderless" :rev :newest)
  :custom
  (completion-styles '(orderless basic))
  ;; (completion-category-defaults nil)
  (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

*** VERTICO
Providing a vertico completion UI for Emacs
Changes to the default configuration are swapping the direction so that the completion is always at the bottom.

[[https://github.com/minad/vertico][GitHub - minad/vertico: :dizzy: vertico.el - VERTical Interactive COmpletion]]

#+begin_src emacs-lisp
(use-package vertico
  :vc (:url "https://github.com/minad/vertico" :rev :newest)
  :custom
  (vertico-cycle t)
  (vertico-resize t)
  (vertico-buffer-display-action
   '(display-buffer-in-direction (direction . right)))
  
  (context-menu-mode t)
  (enable-recursive-minibuffers t)
  (minibuffer-prompt-properties
   '(read-only t cursor-intangible t face minibuffer-prompt))

  :preface
  (defun crm-indicator (args)
        (cons (format "[CRM%s] %s"
                      (replace-regexp-in-string
                       "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                       crm-separator)
                      (car args))
              (cdr args)))
  (advice-add #'completing-read-multiple :filter-args #'crm-indicator)
  
  :config
  (require 'vertico-repeat)
  (add-to-list 'savehist-additional-variables 'vertico-repeat-history)

  (require 'vertico-directory)
  (require 'vertico-quick)

  (vertico-mode)
  
  :bind
  ("C-c r" . vertico-repeat)
  (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("M-DEL" . vertico-directory-delete-word)
              ("C-q" . vertico-quick-insert)
              ("M-q" . vertico-quick-exit))
  :hook
  (minibuffer-setup . vertico-repeat-save)
  (rfn-eshadow-update-overlay . vertico-directory-tidy))
#+end_src

*** MARGINALIA

#+begin_src emacs-lisp
(use-package marginalia
    :vc (:url "https://github.com/minad/marginalia" :rev :newest)
  :bind (:map minibuffer-local-map
         ("M-A" . marginalia-cycle))
  :config
  (marginalia-mode))
#+end_src

*** CONSULT

#+begin_src emacs-lisp
(use-package consult
    :vc (:url "https://github.com/minad/consult" :rev :newest)
    :bind (;;; C-c bindings in `mode-specific-map'
           ("C-c M-x" . consult-mode-command)
           ("C-c h" . consult-history)
           ("C-c k" . consult-kmacro)
           ("C-h M" . consult-man)
           ;; orig. describe-input-method
           ("C-h I" . consult-info) 
           ([remap Info-search] . consult-info)

           ("C-c i" . consult-org-heading)
           
         ;;; C-x bindings in `ctl-x-map'
           ;; orig. repeat-complex-command
           ("C-x M-:" . consult-complex-command)
           ;; orig. switch-to-buffer
           ("C-x b" . consult-buffer)
           ;; orig. switch-to-buffer-other-window
           ("C-x 4 b" . consult-buffer-other-window)
           ;; orig. switch-to-buffer-other-frame
           ("C-x 5 b" . consult-buffer-other-frame)
           ;; orig. switch-to-buffer-other-tab
           ("C-x t b" . consult-buffer-other-tab)
           ;; orig. bookmark-jump
           ("C-x r b" . consult-bookmark)            
           
         ;;; Custom M-# bindings for fast register access
           ("M-#" . consult-register-load)
           ;; orig. abbrev-prefix-mark (unrelated)
           ("M-'" . consult-register-store)          
           ("C-M-#" . consult-register)
           
         ;;; Other custom bindings
           ;; orig. yank-pop
           ("M-y" . consult-yank-pop)                

           :map project-prefix-map
           ;; orig. project-switch-to-buffer
           ("b" . consult-project-buffer)
           
           ;; consult-ripgrep defaults to project root if it decides its in a project
           ;; to interactively set where to start the ripgrep call it with the universal
           ;; prefix
           ;; orig. project-find-regexp
           ("g" . consult-ripgrep)             
           
           :map search-map
           ;; M-s bindings in `search-map'
           ("f" . consult-fd)
           ("c" . consult-locate)
           ("g" . consult-ripgrep)
           ("G" . consult-git-grep)
           ("l" . consult-line)
           ("L" . consult-line-multi)
           ("k" . consult-keep-lines)
           ("u" . consult-focus-lines)
           ;; Isearch integration
           ("e" . consult-isearch-history)

           ;; M-g bindings in `goto-map' 
           :map goto-map
           ("e" . consult-compile-error)
           ;; Alternative: consult-flycheck
           ("f" . consult-flymake)
           ("F" . (lambda () (interactive) (consult-flymake '(4))))
           ;; Alternative: consult-org-heading
           ("o" . consult-outline)
           ("m" . consult-mark)
           ("k" . consult-global-mark)
           ("i" . consult-imenu)
           ("I" . consult-imenu-multi)
           ("L" . consult-goto-line)
           
           :map isearch-mode-map
           ("M-e" . consult-isearch-history)
           ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch-history)
           ;; needed by consult-line to detect isearch
           ("M-s l" . consult-line)
           ;; needed by consult-line to detect isearch
           ("M-s L" . consult-line-multi)
           
           ;; Minibuffer history
           :map minibuffer-local-map
           ;; orig. next-matching-history-element
           ("M-s" . consult-history)
           ;; orig. previous-matching-history-element
           ("M-r" . consult-history))                

    :hook (completion-list-mode . consult-preview-at-point-mode)

    :init
    (setq register-preview-delay 0.5
          register-preview-function #'consult-register-format)

    (advice-add #'register-preview :override #'consult-register-window)

    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)

    :config

    (setq consult-ripgrep-args (concat consult-ripgrep-args " --follow"))

    (consult-customize
     consult-theme :preview-key '(:debounce 0.2 any)
     consult-ripgrep consult-git-grep consult-grep
     consult-bookmark consult-recent-file
     consult--source-bookmark consult--source-file-register
     consult--source-recent-file consult--source-project-recent-file
     :preview-key '(:debounce 0.4 any))

    (setq consult-narrow-key "<"))
#+end_src

*** EMBARK
Easily run commands based on the context of where the point is [[https://github.com/oantolin/embark][GitHub - Emacs Mini-Buffer Actions Rooted in Keymaps]]

#+begin_src emacs-lisp
(use-package embark
    :vc (:url "https://github.com/oantolin/embark" :rev :newest)
    :after avy
    :custom
    (embark-cycle-key (kbd "C-."))
    :hook
    (embark-collect-mode . embark-collect-direct-action-minor-mode)
    :bind
    (("C-." . embark-act)         
     ("C-;" . embark-dwim)        
     ("C-h B" . embark-bindings))

    :init
    (setq prefix-help-command #'embark-prefix-help-command)

    :config
    (defun avy-action-embark (pt)
      (unwind-protect
           (save-excursion
             (goto-char pt)
             (embark-act))
        (select-window
         (cdr (ring-ref avy-ring 0))))
      t)

    (defun avy-action-embark-dwim (pt)
      (unwind-protect
           (save-excursion
             (goto-char pt)
             (embark-dwim))
        (select-window
         (cdr (ring-ref avy-ring 0))))
      t)
    
    (setf (alist-get ?. avy-dispatch-alist) 'avy-action-embark)
    (setf (alist-get ?\; avy-dispatch-alist) 'avy-action-embark-dwim)

    (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
    (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)
    
    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

;; Consult users will also want the embark-consult package.
(use-package embark-consult
    :hook
  (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

Combining embark with avy is one of the break through moments of my usage of this package. As is often the case this is a moment of discovery followed by months of incomprehension until finally a dawning understanding
[[https://karthinks.com/software/avy-can-do-anything/#a-division-of-responsibility][Avy can do anything | Karthinks]]

*** CORFU

#+begin_src emacs-lisp
(use-package corfu
  :vc (:url "https://github.com/minad/corfu" :rev :newest)
  :custom
  (corfu-cycle t)
  (corfu-popupinfo-hide nil)
  (corfu-scroll-margin 5)                 ;; Additional scroll margin
  ;;cape-dict
  (text-mode-ispell-word-completion nil)
  :bind
  (:map corfu-map
        ("M-q" . corfu-quick-complete))
  :hook
  ;; Configure Corfu for eshell-mode
  (eshell-mode . (lambda ()
                   (setq-local corfu-auto nil)
                   (corfu-mode)))
  :config
  (require 'corfu-history)
  (corfu-history-mode)
  (require 'corfu-quick)
  (require 'corfu-popupinfo)
  (corfu-popupinfo-mode)

  ;; Define a repeat map for corfu-popupinfo navigation
  (defvar corfu-popupinfo-navigation-repeat-map
    (let ((map (make-sparse-keymap)))
      (keymap-set map "n" #'corfu-popupinfo-scroll-up)
      (keymap-set map "p" #'corfu-popupinfo-scroll-down)
      (keymap-set map ">" #'corfu-popupinfo-end)
      (keymap-set map "<" #'corfu-popupinfo-beginning)
      (keymap-set map "d" #'corfu-popupinfo-documentation)
      (keymap-set map "l" #'corfu-popupinfo-location)
      (keymap-set map "t" #'corfu-popupinfo-toggle)
      map)
    "Repeat map for Corfu popupinfo navigation commands.")

  ;; Register commands with the repeat map
  (dolist (cmd '(corfu-popupinfo-scroll-up
                 corfu-popupinfo-scroll-down
                 corfu-popupinfo-end
                 corfu-popupinfo-beginning
                 corfu-popupinfo-documentation
                 corfu-popupinfo-location
                 corfu-popupinfo-toggle))
    (put cmd 'repeat-map 'corfu-popupinfo-navigation-repeat-map))

  ;; Set up the C-h prefix binding in corfu-map
  (keymap-set corfu-map "C-h" (define-keymap
                                "n" #'corfu-popupinfo-scroll-up
                                "p" #'corfu-popupinfo-scroll-down
                                ">" #'corfu-popupinfo-end
                                "<" #'corfu-popupinfo-beginning
                                "d" #'corfu-popupinfo-documentation
                                "l" #'corfu-popupinfo-location
                                "t" #'corfu-popupinfo-toggle))
  
  (defun corfu-move-to-minibuffer ()
    (interactive)
    (pcase completion-in-region--data
      (`(,beg ,end ,table ,pred ,extras)
        (let ((completion-extra-properties extras)
              completion-cycle-threshold completion-cycling)
          (consult-completion-in-region beg end table pred)))))
  (keymap-set corfu-map "M-m" #'corfu-move-to-minibuffer)
  (add-to-list 'corfu-continue-commands #'corfu-move-to-minibuffer)

  (keymap-set corfu-map "RET" #'corfu-send)
  
  (global-corfu-mode))
#+end_src

#+begin_src emacs-lisp
(use-package corfu-candidate-overlay
    :vc (:url "https://code.bsdgeek.org/adam/corfu-candidate-overlay" :rev :newest)
    :after corfu
    :config
    (corfu-candidate-overlay-mode +1))
#+end_src

*** CAPE

#+begin_src emacs-lisp
(use-package cape
    :vc (:url "https://github.com/minad/cape" :rev :newest)
    :bind ("C-c p" . cape-prefix-map) 
    :config
    (require 'cape-char)
    (require 'cape-keyword)

    (defun my-completion-at-point ()
      (cape-wrap-super
       #'cape-abbrev
       #'cape-dabbrev
       #'cape-dict
       #'cape-emoji))

    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'my-completion-at-point))
    #+end_src

*** TEMPEL

#+begin_src emacs-lisp
(use-package tempel
    :vc (:url "https://github.com/minad/tempel" :rev :newest)
    :custom
    (tempel-trigger-prefix "<")

  :bind (("M-+" . tempel-complete) ;; Alternative tempel-expand
         ("M-*" . tempel-insert))

  :config
  (global-tempel-abbrev-mode))
#+end_src

#+begin_src emacs-lisp
(use-package tempel-collection
    :vc (:url "https://github.com/Crandel/tempel-collection" :rev :newest)
    :after tempel)
#+end_src

*** ICONS

#+begin_src emacs-lisp
(use-package nerd-icons-completion
    :vc (:url "https://github.com/rainstormstudio/nerd-icons-completion" :rev :newest)
  :after marginalia
  :config
  (nerd-icons-completion-mode)
  :hook
  (marginalia-mode . nerd-icons-completion-marginalia-setup))

(use-package nerd-icons-corfu
    :vc (:url "https://github.com/LuigiPiucco/nerd-icons-corfu" :rev :newest)
  :after corfu
  :config
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

** TOOLS

*** PDF TOOLS
#+begin_src emacs-lisp
(use-package pdf-tools
  :vc (:url "https://github.com/vedang/pdf-tools" :rev :newest)
  :config
  (pdf-tools-install))
#+end_src

*** AI :: LLM :: GPTEL
**** AI CODE INTERFACE

#+begin_src emacs-lisp
(use-package ai-code-interface
  :straight (:host github :repo "tninja/ai-code-interface.el")
  :config
  (ai-code-set-backend  'claude-code-ide) ;; use claude-code-ide as backend
  ;; Enable global keybinding for the main menu
  (global-set-key (kbd "C-c a") #'ai-code-menu)
  ;; Optional: Set up Magit integration for AI commands in Magit popups
  (with-eval-after-load 'magit
    (ai-code-magit-setup-transients)))
#+end_src

**** GPTEL

#+begin_src emacs-lisp
(use-package gptel
    :vc (:url "https://github.com/karthink/gptel" :rev :newest)
    :after embark
    :commands (gptel gptel-menu gptel-send gptel-request gptel-add)
    :config
    (require 'gptel-integrations)
        
    (gptel-make-anthropic "Claude"
                          :key gptel-api-key
                          :stream t)
    
    (gptel-make-anthropic "Claude-thinking" ;Any name you want
      :key gptel-api-key
      :stream t
      :models '(claude-3-7-sonnet-20250219 claude-3-opus-20240229)
      :header (lambda () (when-let* ((key (gptel--get-api-key)))
                           `(("x-api-key" . ,key)
                             ("anthropic-version" . "2023-06-01")
                             ("anthropic-beta" . "pdfs-2024-09-25")
                             ("anthropic-beta" . "output-128k-2025-02-19")
                             ("anthropic-beta" . "prompt-caching-2024-07-31"))))
      :request-params '(:thinking (:type "enabled" :budget_tokens 2048)
                        :max_tokens 4096))

    (gptel-make-gemini "Gemini" :key gptel-api-key :stream t)

    (setq
     gptel-model 'claude-3-sonnet-20240229
     gptel-backend (cdr (assoc "Claude" gptel--known-backends)))
    
    ;; Doesnt work for some reason
    ;; (setq gptel-log-level 'debug)

    (setq gptel-default-mode 'org-mode)
    (add-to-list 'auto-mode-alist '("\\.llm\\'" . org-mode))

    (define-abbrev-table 'gptel-mode-abbrev-table
        '(("eyt" "explain your thinking step by step" nil :count 0)))

    (add-hook 'gptel-mode-hook (lambda ()
                                 (setq local-abbrev-table gptel-mode-abbrev-table)))
    
    :bind
    ("C-c RET" . gptel-send)
    ("C-, s" . gptel-send)
    ("C-, A" . gptel-abort)
    ("C-, a" . gptel-add)
    ("C-, m" . gptel-menu)
    ("C-, q" . gptel-quick)

    :hook
    (org-mode . (lambda () 
                  (when (and buffer-file-name
                             (string-match-p "\\.llm\\'" buffer-file-name))
                    (gptel-mode 1)))))
#+end_src

***** GPTEL QUICK

#+begin_src emacs-lisp
(use-package gptel-quick
    :vc (:url "https://github.com/karthink/gptel-quick" :rev :newest)
    :after gptel embark
    :bind (:map embark-general-map
                ("?" . gptel-quick))
    :config
(defun gptel-quick--update-posframe-with-custom-border (orig-fun &rest args)
  "Temporarily modify border for gptel-quick posframe during update."
  (let ((face-attribute-orig (face-attribute 'vertical-border :foreground)))
    (set-face-attribute 'vertical-border nil :foreground (face-attribute 'child-frame-border :background))
    (apply orig-fun args)
    (set-face-attribute 'vertical-border nil :foreground face-attribute-orig)))

(advice-add 'gptel-quick--update-posframe :around #'gptel-quick--update-posframe-with-custom-border))
#+end_src

**** MCP

#+begin_src emacs-lisp
(use-package mcp
    :vc (:url "lizqwerscott/mcp.el" :rev :newest)
    :after gptel
    :custom (mcp-hub-servers
             `(("filesystem" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-filesystem" (getenv "HOME"))))
             ("fetch" . (:command "uvx" :args ("mcp-server-fetch")))))
  :config (require 'mcp-hub)
  :hook (after-init . mcp-hub-start-all-server))
#+end_src

*** DAEMONS
Emacs UI for managing init systems, in my case just systemd needs a poke
#+begin_src emacs-lisp
(use-package daemons
    :vc (:url "https://github.com/cbowdon/daemons.el" :rev :newest))
    #+end_src

*** JOURNALCTL

#+begin_src emacs-lisp
(use-package journalctl-mode
    :vc (:url "https://github.com/WJCFerguson/journalctl" :rev :newest)
  :bind (("C-c t" . journalctl)))
#+end_src

*** EWW

#+begin_src emacs-lisp
(use-package eww
    :bind
  ("s-w" . eww))
#+end_src

*** RECALL

#+begin_src emacs-lisp
  (use-package recall
    :vc (:url "https://github.com/svaante/recall" :rev
    :ensure t
    :bind
    ("C-x C-r" . recall-rerun)
    :custom
    ;; Consult completion based interface
    (recall-completing-read-fn #'recall-consult-completing-read)
    (recall-save-file (concat no-littering-var-directory "recall/history"))
    (recall-directory (concat no-littering-var-directory "recall/"))
    :config
    ;; Enable process surveillance
    (recall-mode +1))
#+end_src

*** ASYNC SHELL

#+begin_src emacs-lisp
(use-package async-shell
    :vc (:url "https://github.com/sgpthomas/async-shell" :rev)
    :bind
    ([remap shell-command] . async-launch-shell)
    :config
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((async-shell . t))))
#+end_src

*** VTERM
[[https://github.com/akermu/emacs-libvterm][GitHub - akermu/emacs-libvterm: Emacs libvterm integration]]

This is a terminal emulator without the quirks of eshell

Used for any visual commands.
#+begin_src emacs-lisp
(use-package vterm)
#+end_src

** PROJECT
#+begin_src emacs-lisp
  (use-package project
    :after consult

    :config
    ;; use consult-ripgrep instead of project-find-regexp in project.el 
    (require 'keymap) 
    (require 'cl-seq)

    (keymap-substitute project-prefix-map #'project-find-regexp #'consult-ripgrep)
    (cl-nsubstitute-if
     '(consult-ripgrep "Find regexp")
     (pcase-lambda (`(,cmd _)) (eq cmd #'project-find-regexp))
     project-switch-commands))
#+end_src

** MODES
*** ORG MODE

#+begin_src emacs-lisp 
(use-package org
    :after (cape tempel)
    :bind
  ("C-c l" . org-store-link)
    :hook
  ((org-mode . visual-line-fill-column-mode)
   (org-mode . adaptive-wrap-prefix-mode)))
#+end_src

*** AGENDA

#+begin_src emacs-lisp 
(use-package org-agenda
    :ensure nil
    :after org
   :config
   (require 'org-agenda))
#+end_src

*** CAPTURE

#+begin_src emacs-lisp 
(use-package org-capture
  :ensure nil
  :after org
  :custom
  (org-default-notes-file (concat org-directory "/calendar.org"))
  :config
  (setq org-capture-templates
        '(("e" "Events")
          ("ep" "Personal event" entry
           (file+headline "calendar.org" "Personal")
           "* %^{Event}\n%^T\n%?\n"
           :empty-lines-before 1
           :append t)
         )))
#+end_src

*** ORG STREET

[[https://codeberg.org/emacs-weirdware/org-street][emacs-weirdware/org-street: Add geocoded LOCATION properties to Org entries - Codeberg.org]]

This package adds a nice way to add a location to a scheduled org header using OpenStreetMap

#+begin_src emacs-lisp 
(use-package org-steet
    :after org
    :vc (:url "https://codeberg.org/emacs-weirdware/org-street" :rev :newest)
    :bind
  ("C-c l" . org-store-link)
    :hook
  ((org-mode . visual-line-fill-column-mode)
   (org-mode . adaptive-wrap-prefix-mode)))
#+end_src

*** MARKDOWN MODE

#+begin_src emacs-lisp 
(use-package markdown-mode
    :vc (:url "https://github.com/jrblevin/markdown-mode" :rev :newest)
  :mode ("README\\.md\\'" . gfm-mode)
  :bind
  (:map markdown-mode-map
        ("C-c V" . markdown-view-mode))
  (:map markdown-view-mode-map
        ("C-c V" . markdown-mode))
  (:map markdown-mode-map
        ("C-c v" . gfm-view-mode))
  (:map gfm-view-mode-map
        ("C-c v" . gfm-mode))
  :custom
  (markdown-command "multimarkdown")
  :hook
  (markdown-mode . visual-fill-column-mode)
  (markdown-view-mode . visual-fill-column-mode))
 #+end_src
 
*** TEXT MODE

#+begin_src emacs-lisp 
(use-package text-mode
    :ensure nil
    :hook
    ((text-mode . visual-line-fill-column-mode)
     (text-mode . adaptive-wrap-prefix-mode)))
#+end_src

** PROGRAMMING

#+begin_src emacs-lisp
(use-package emacs
  :custom
  (electric-pair-mode t)
  :bind
  (:map prog-mode-map
        ("C-c l" . display-line-numbers-mode)))
#+end_src

*** GIT
**** MAGIT
#+begin_src emacs-lisp
(use-package magit
    :vc (:url "https://github.com/magit/magit" :rev :newest)
    :config
    ;; Makes Ediff much more usable
  (ediff-window-setup-function 'ediff-setup-windows-plain)
  :bind (("s-m m" . magit-status)
         ("s-m j" . magit-dispatch)
         ("s-m k" . magit-file-dispatch)
         ("s-m l" . magit-log-buffer-file)
         ("s-m b" . magit-blame)))
#+end_src 

**** FORGE
#+begin_src emacs-lisp
(use-package forge
    :vc (:url "https://github.com/magit/forge" :rev :newest)
    :after magit

    ***REMOVED***
  :bind (("s-m m" . magit-status)
         ("s-m j" . magit-dispatch)
         ("s-m k" . magit-file-dispatch)
         ("s-m l" . magit-log-buffer-file)
         ("s-m b" . magit-blame)))
#+end_src 

**** GIT MODES
#+begin_src emacs-lisp
(use-package git-modes
    :vc (:url "https://github.com/magit/git-modes" :rev :newest)
  :mode
  ("/\\.dockerignore\\'" . gitignore-mode))
#+end_src

*** HTTP REQUESTS :: VERB

For all those API's out there

This is the (spiritual) successor to [[https://github.com/pashky/restclient.el][restclient.el]]
#+begin_src emacs-lisp
(use-package verb
  :config (define-key org-mode-map (kbd "C-c C-r") verb-command-map)
(org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((verb . t)))))
#+end_src

*** EGLOT (LSP)

#+begin_src emacs-lisp
  (use-package eglot
      :custom
    (eglot-ignored-server-capabilities
     '(:documentFormattingProvider
       :documentRangeFormattingProvider
       :documentOnTypeFormattingProvider))
    :config
    (with-eval-after-load 'eglot
     (setq completion-category-defaults nil))

    (advice-add 'eglot-completion-at-point :around #'cape-wrap-buster)

    (defun my/eglot-capf ()
    (setq-local completion-at-point-functions
                (list (cape-capf-super
                       #'eglot-completion-at-point
                       #'cape-abbrev))))

  (add-hook 'eglot-managed-mode-hook #'my/eglot-capf)

  :bind
  (:map eglot-mode-map
        ("C-c r" . eglot-rename)
        ("C-c o" . eglot-code-action-organize-imports)
        ("C-c a" . eglot-code-actions)
        ("C-c i" . eglot-inlay-hints-mode)))
#+end_src

#+begin_src emacs-lisp
(use-package consult-eglot
    :vc (:url "https://github.com/mohkale/consult-eglot" :rev :newest)
    :after (eglot consult)
    ;; TODO
    ;; :bind
    ;; consult-eglot-symbols
    :config
    (require 'consult-eglot-embark)
    (consult-eglot-embark-mode))
#+end_src

#+begin_src emacs-lisp
  (use-package eglot-tempel
    :vc (:url "https://github.com/fejfighter/eglot-tempel" :rev :newest)
    :after (eglot tempel)
    :config
    (eglot-tempel-mode t))
#+end_src

*** FORMATTING

#+begin_src emacs-lisp
  (use-package apheleia
    :vc (:url "https://github.com/radian-software/apheleia" :rev :newest)
    :config 
    (apheleia-global-mode +1))
#+end_src

*** COMPILATION
#+begin_src emacs-lisp
  (use-package fancy-compilation
        :vc (:url "https://codeberg.org/ideasman42/emacs-fancy-compilation" :rev :newest)
        :after compile
    :custom
    (fancy-compilation-override-colors nil)
    (fancy-compilation-quiet-prelude nil)
    :config
    (fancy-compilation-mode))
#+end_src

**** XTERM COLOR

#+begin_src emacs-lisp
(use-package xterm-color
  :vc (:url "https://github.com/atomontage/xterm-color" :rev :newest)
  :config
  (setq compilation-environment '("TERM=xterm-256color"))
  (defun my/advice-compilation-filter (f proc string)
    (funcall f proc (xterm-color-filter string)))
  (advice-add 'compilation-filter :around #'my/advice-compilation-filter))
#+end_src

*** QUICK RUN
[[https://github.com/emacsorphanage/quickrun][Run command quickly. This packages is inspired quickrun.vim]]

#+begin_src emacs-lisp
(use-package quickrun
  :vc (:url "https://github.com/emacsorphanage/quickrun" :rev :newest)
  :config
  (quickrun-add-command "typescript/tsx"
    '((:command . "tsx")
      (:exec . "%c %s %a")
      (:description . "Run TypeScript with tsx")
      (:mode typescript-ts-mode))
    :default "typescript"))
#+end_src

*** ENVRC :: DIRENV
#+begin_src emacs-lisp
(use-package envrc
  :vc (:url "https://github.com/purcell/envrc" :rev :newest)
  :config
  (envrc-global-mode))
#+end_src

*** SHELL :: BASH

#+begin_src emacs-lisp
(use-package sh-mode
  :ensure nil
  :no-require

  :mode
  ("/scripts/" . sh-mode)
  (".env" . sh-mode)

  :hook
  ;; Make shebang (#!) file executable when saved
  (after-save . executable-make-buffer-file-executable-if-script-p)

  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((shell . t)))))
#+end_src

*** FLYMAKE

#+begin_src emacs-lisp
(use-package flymake
  :ensure nil
  :bind
  (:map flymake-mode-map
        ("M-n" . flymake-goto-next-error)
        ("M-p" . flymake-goto-prev-error)))
#+end_src

** APPLICATIONS

*** EMENT (MATRIX)
#+begin_src emacs-lisp
(use-package ement
  :vc (:url "https://github.com/alphapapa/ement.el" :rev :newest))
#+end_src

*** LANGUAGES

**** EMACS LISP
#+begin_src emacs-lisp
(use-package emacs
    :custom
  (lisp-indent-function 'common-lisp-indent-function))
#+end_src

**** NIX

#+begin_src emacs-lisp
  (use-package nix-mode
    :custom
    (nix-prettify-global-mode t)
    (nix-prettify-char "❅")
    (nix-prettify-regexp "/nix/\\(?:log\\|nar\\|store\\)/\\([0-9a-df-np-sv-z]\\{32\\}\\)")
    (nix-prettify-regexp-group 0)

    ;; Call direnv after initing flake
    (nix-flake-init-post-action
     (lambda ()
       (direnv-allow)
       (find-file "flake.nix")))

    :hook
    (nix-mode . eglot-ensure)

    :init
    ;; Some custom functions to ease my life
(defun nix-rebuild-system+ (&optional host)
  "Build Nixos HOST. Defaults to function `system-name'."
  (interactive)
  (let ((compilation-scroll-output t)
        (default-directory "/sudo::/home/inkpotmonkey/.config/nixos")
        (compilation-buffer-name-function
         (lambda (_) (concat "*" (symbol-name this-command) "*")))
        (show-trace (if current-prefix-arg "--show-trace" "")))
    (direnv--clear (buffer-name))
    (compile
     (format "nixos-rebuild switch %s --flake .#%s" show-trace system-name))))

    (defun nix-update-system-flake+ (&optional flake-path)
    "Update a flake. Defaults to system flake."
    (interactive)
    (let ((default-directory "~/.config/nixos")
          (compilation-buffer-name-function
           (lambda (_) (concat "*" (symbol-name this-command) "*"))))
      (direnv--clear (buffer-name))
      (compile (concat "nix flake update --flake " (or flake-path default-directory))))))
#+end_src

#+begin_src emacs-lisp
(use-package nix-ts-mode)
#+end_src

A package to easily update fetch hash's.

Doesn't seem to work or I am using it wrong.
#+begin_src emacs-lisp
(use-package nix-update)
#+end_src

A side project to get bash highlighting in nix mode files
[[https://www.masteringemacs.org/article/polymode-multiple-major-modes-how-to-use-sql-python-in-one-buffer][Polymode: Multiple Major Modes and How to Use SQL and Python in one Buffer - Mastering Emacs]]
#+begin_src emacs-lisp
(use-package polymode
  :disabled)
;;:mode ("\.nix$" . poly-nix-mode)
;;:config
;;(setq polymode-prefix-key (kbd "C-c n"))
;;(define-hostmode poly-nix-hostmode :mode 'nix-mode)

;; (define-innermode poly-nix-expr-bash-innermode
;;                   :mode 'bash-ts-mode
;;                   :head-matcher "installPhase.+$"
;;                   :tail-matcher "..;$"
;;                   :head-mode 'host
;;                   :tail-mode 'host
;;                   ))
#+end_src

*****  OB NIX

A way to explore nix code via org source blocks
[[https://codeberg.org/theesm/ob-nix][⛰ theesm/ob-nix]]

#+begin_src emacs-lisp
(use-package ob-nix
  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((nix . t)))))
#+end_src

e.g.
#+begin_src nix 
rec { x = "foo"; y = x; }
#+end_src

**** RUST
Moving to a much more minimal setup with the main functionalities provided by the in built tree sitter for syntax highlighting and eglot + rust analyser for code support.

Plus all formatting as usual is handled by Apheleia.

Eglot clobbers all flymake checkers but we can set the diagnostic command to clippy in the rust analyser lsp initialization options so we don't need to fiddle with merging multiple diagnostic providers. This is outlined in the [[https://rust-analyzer.github.io/manual.html#eglot][Rust Analyzer User Manual]].

We also add ~Cargo.toml~ to the ~project-vc-extra-root-markers~ variable so that the rust analyser can start up in projects where the rust part of it is nested. Otherwise it only picks up projects where the rust project is in the top level. This is only an imperfect fix though as it restricts the file/buffer searching and more...

#+begin_src emacs-lisp
(use-package rust-ts-mode
  :ensure nil
  :hook
  (rust-ts-mode . eglot-ensure)
  
  :config
  (add-to-list 'eglot-server-programs
               '((rust-ts-mode rust-mode) .
                 ("rust-analyzer"
                  :initializationOptions
                  (:check (:command "clippy")))))
  
  (add-to-list 'project-vc-extra-root-markers "Cargo.toml"))
#+end_src

#+begin_src emacs-lisp 
(use-project rust
  :p "Cargo.toml"
  :map ("C-c p" 'cargo-transient))
#+end_src

***** CARGO

Eventually this should be replace by my personal rust mode

#+begin_src emacs-lisp
(use-package cargo-transient
  :bind
  (:map rust-ts-mode-map
        ("C-c c" . cargo-transient))
  :custom
  (cargo-transient-compilation-buffer-name-function 'project-prefixed-buffer-name))
#+end_src

***** PERSONAL RUST MODE
The start of my own personal rust mode:

This finds all the macro declarations of test
TODO: Get function name of test below this macro
TODO: Create completion list with these function names callable via consult
TODO: Feed the completion choice into a cargo command to only call a single test
TODO: Add way to quickly call last completed test
#+begin_src emacs-lisp
(defun get-rust-test-functions-in-file (file)
  (let ((buffer (find-file-noselect file)))
    (with-current-buffer buffer)
    (let* ((root-node (treesit-buffer-root-node))
           (query '((attribute_item
                     (attribute (identifier) @test)
                     (:equal @test "test"))))
           (queries (treesit-query-capture root-node query))))))
#+end_src

**** SHELL :: BASH

I have a habit of sticking project specific bash scripts under a scripts folder in each project. The ~mode~ directive of use-package here states that any file under a folder called =scripts= should use the ~sh-mode~, the Emacs wiki is a great reference for this [[https://www.emacswiki.org/emacs/AutoModeAlist#h5o-7][EmacsWiki: Auto Mode Alist]]. This may need to be tweaked if I create any scripts in different languages. Especially if I start using [[https://nixos.org/manual/nix/stable/command-ref/new-cli/nix.html#shebang-interpreter][nix shebang-interpreters]] more.

#+begin_src emacs-lisp
(use-package sh-mode
  :ensure nil
  :no-require

  :mode
  ("/scripts/" . sh-mode)
  (".env" . sh-mode)

  :hook
  ;; Make shebang (#!) file executable when saved
  (after-save . executable-make-buffer-file-executable-if-script-p)

  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((shell . t)))))
#+end_src

**** WEB
***** JAVASCRIPT :: NODE

#+begin_src emacs-lisp
(use-package js-ts-mode
  :mode "\\.cjs\\'"
  :ensure nil
  :no-require
  :init
  (push '(javascript-mode . js-ts-mode) major-mode-remap-alist)
  :custom
  (global-subword-mode t)
  :hook
  (js-ts-mode . eglot-ensure))
#+end_src

#+begin_src emacs-lisp
(use-package nodejs-repl)
#+end_src

***** TYPESCRIPT / JSX / TSX

I like to see new packages taking advantage of treesitter [[https://github.com/llemaitre19/jtsx][ llemaitre19/jtsx]]. This still needs to be fully explored:

Disabled as I am no longer writing any JSX / TSX

#+begin_src emacs-lisp
(use-package jtsx
    :disabled
  :mode (("\\.jsx?\\'" . jtsx-jsx-mode)
         ("\\.tsx\\'" . jtsx-tsx-mode)
         ("\\.ts\\'" . jtsx-typescript-mode))
  
  :hook ((jtsx-jsx-mode . hs-minor-mode)
         (jtsx-tsx-mode . hs-minor-mode)
         (jtsx-typescript-mode . hs-minor-mode))
  
  ;; :custom
  ;; Optional customizations
  ;; (js-indent-level 2)
  ;; (typescript-ts-mode-indent-offset 2)
  ;; (jtsx-switch-indent-offset 0)
  ;; (jtsx-indent-statement-block-regarding-standalone-parent nil)
  ;; (jtsx-jsx-element-move-allow-step-out t)
  ;; (jtsx-enable-jsx-electric-closing-element t)
  ;; (jtsx-enable-electric-open-newline-between-jsx-element-tags t)
  ;; (jtsx-enable-jsx-element-tags-auto-sync nil)
  ;; (jtsx-enable-all-syntax-highlighting-features t)
  
  :config
  (defun jtsx-bind-keys-to-mode-map (mode-map)
    "Bind keys to MODE-MAP."
    (define-key mode-map (kbd "C-c C-j") 'jtsx-jump-jsx-element-tag-dwim)
    (define-key mode-map (kbd "C-c j o") 'jtsx-jump-jsx-opening-tag)
    (define-key mode-map (kbd "C-c j c") 'jtsx-jump-jsx-closing-tag)
    (define-key mode-map (kbd "C-c j r") 'jtsx-rename-jsx-element)
    (define-key mode-map (kbd "C-c <down>") 'jtsx-move-jsx-element-tag-forward)
    (define-key mode-map (kbd "C-c <up>") 'jtsx-move-jsx-element-tag-backward)
    (define-key mode-map (kbd "C-c C-<down>") 'jtsx-move-jsx-element-forward)
    (define-key mode-map (kbd "C-c C-<up>") 'jtsx-move-jsx-element-backward)
    (define-key mode-map (kbd "C-c C-S-<down>") 'jtsx-move-jsx-element-step-in-forward)
    (define-key mode-map (kbd "C-c C-S-<up>") 'jtsx-move-jsx-element-step-in-backward)
    (define-key mode-map (kbd "C-c j w") 'jtsx-wrap-in-jsx-element)
    (define-key mode-map (kbd "C-c j u") 'jtsx-unwrap-jsx)
    (define-key mode-map (kbd "C-c j d") 'jtsx-delete-jsx-node))
  
  (defun jtsx-bind-keys-to-jtsx-jsx-mode-map ()
    (jtsx-bind-keys-to-mode-map jtsx-jsx-mode-map))

  (defun jtsx-bind-keys-to-jtsx-tsx-mode-map ()
    (jtsx-bind-keys-to-mode-map jtsx-tsx-mode-map))

  (add-hook 'jtsx-jsx-mode-hook 'jtsx-bind-keys-to-jtsx-jsx-mode-map)
  (add-hook 'jtsx-tsx-mode-hook 'jtsx-bind-keys-to-jtsx-tsx-mode-map))
#+end_src

****** TYPESCRIPT
Are any packages worth it beyond the eglot + ts-mode + aphelia + flymake combo?

These settings for the typescript server need to be checked as they were found on Reddit... only play will tell...

[[https://www.reddit.com/r/emacs/comments/11bqzvk/emacs29_and_eglot_inlay_hints/][Reddit - Dive into anything]] - this has a more expansive example

This gives type inlays in my ts/tsx files though tsx types can be a tad overwhelming

#+begin_src emacs-lisp
(use-package typescript-ts-mode
  :ensure nil

  :hook
  ((js-mode
    js-ts-mode
    tsx-ts-mode
    typescript-ts-mode
    typescript-mode
    jtsx-jsx-mode
    jtsx-tsx-mode
    jtsx-typescript-mode) . eglot-ensure)
  
  :config
  (add-to-list
   'eglot-server-programs
   '((js-mode js-ts-mode tsx-ts-mode typescript-ts-mode typescript-mode jtsx-jsx-mode jtsx-tsx-mode jtsx-typescript-mode)
     "typescript-language-server" "--stdio"
     :initializationOptions
     (:preferences
      (:includeInlayParameterNameHints "all"
                                       :includeInlayParameterNameHintsWhenArgumentMatchesName t
                                       :includeInlayFunctionParameterTypeHints t
                                       :includeInlayVariableTypeHints t
                                       :includeInlayVariableTypeHintsWhenTypeMatchesName t
                                       :includeInlayPRopertyDeclarationTypeHints t
                                       :includeInlayFunctionLikeReturnTypeHints t
                                       :includeInlayEnumMemberValueHints t)))))
#+end_src

****** TYPESCRIPT BABEL
For that org goodness

#+begin_src emacs-lisp
(use-package ob-typescript
    :config
  (org-babel-do-load-languages
 'org-babel-load-languages
 '((typescript . t)
   )))
#+end_src

***** EMMET
[[https://docs.emmet.io/][Emmet]] is a great package for lessening the amount of boiler plate needed in writing HTML and CSS. Snippets on steroids is one way of phrasing it.

I need to add this as a extra server / input to Eglot

***** HTML
#+begin_src emacs-lisp
(use-package mhtml-mode
  :disabled
  :ensure nil
  :hook
  (mhtml-mode . eglot-ensure))

(use-package web-mode
  :disabled
  :mode ("\\.html?\\'" . web-mode)
  :hook
  (web-mode . eglot-ensure))

(use-package html-mode
  :no-require
  :ensure nil
  :bind (:map html-mode-map
              ("M-o" . nil)
              ("C-c o O" . font-lock-fontify-block)
              ("C-c o b" . facemenu-set-bold)
              ("C-c o d" . facemenu-set-default)
              ("C-c o i" . facemenu-set-italic)
              ("C-c o l" . facemenu-set-bold-italic)
              ("C-c o o" . facemenu-set-face)
              ("C-c o u" . facemenu-set-underline)))
#+end_src

****** SERVER
A simple web server for development. Has some flaws so always fall back to a different web server if this does not work.

#+begin_src emacs-lisp
(use-package simple-httpd)
#+end_src

****** WEBC

This is a version of web components made for 11ty's webc files. For now we are just using ~html-ts-mode~

#+begin_src emacs-lisp
(use-package webc-mode
  :no-require
  :ensure nil
  :mode ("\\.webc\\'" . html-ts-mode))
#+end_src


***** CSS

#+begin_src emacs-lisp
(use-package css-ts-mode
  :ensure nil
  :no-require
  :after eglot
  :custom
  (css-indent-offset 2)
  :init
  (push '(css-mode . css-ts-mode) major-mode-remap-alist)
  :hook
  (css-ts . eglot-ensure))
#+end_src

***** NPM

#+begin_src emacs-lisp
(use-package npm)
#+end_src

This needs to be expanded to take into account different types of projects such as bun pnpm etc.

#+begin_src emacs-lisp 
(use-project npm
  :p "package.json"
  :map ("C-c p" 'npm))
#+end_src

***** BUN

I seem to be using Bun more and more. This presents a problem when packages assume Node.js. This fake package is a fix for some of those assumptions and a collection of niceties.

Even though I set these via `dir-locals-set-class-variables' they are still set locally. How can I set these only for the relevant directory? Or alternatively if I just keep overriding them does it matter?

This ~bun-with-npm+~ is a poor mans implementation and a from scratch version would be much better

#+begin_src emacs-lisp
(use-package bun
  :no-require
  :ensure nil
  :after project
  :config

  (defun bun-with-npm+ ()
    "Replace `npm` with `bun` in the npm transient commands."
    (dolist (var '(npm-run--prefix-command
                   npm-init--prefix-command
                   npm-update--prefix-command
                   npm-install--prefix-command
                   npm-publish--prefix-command))
      (set var
           (replace-regexp-in-string "npm" "bun"
                                     (symbol-value var)))))

  (defun setup-bun-project+ ()
    "Set up bun project."
    (interactive)
    (when (bun-project-p+)
      (progn
        (bun-with-npm+))))

  (defun bun-project-p+ ()
    (let ((project-root (project-root (project-current))))
      (file-exists-p (concat project-root "bun.lockb"))))

  ;;TODO: Add in toggling
  ;;TODO: Add in exiting if called not in a bun project
  (defun bun-find-other-file-test+ ()
    "Functions a bit like `ff-find-other-file' expect that it toggles between the bun test file and the original file."
    (interactive)
    (let* ((project-root (project-root (project-current))))
      ((test-file
        (concat project-root
                "tests/"
                (file-name-sans-extension (buffer-name))
                ".test.ts")))
      (find-file test-file)))
  )
#+end_src

***** LOREM IPSUM

#+begin_quote
Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC.

-- [[https://www.lipsum.com/][Lorem Ipsum - All the facts - Lipsum generator]]
#+end_quote

How the mighty has fallen, from a text about the Extremes of Good and Evil to be become the default filler of the modern web.

Another interesting article on the Ipsum is [[https://loremipsum.io/][Lorem Ipsum – Generator, Origins and Meaning]]

#+begin_src emacs-lisp
(use-package lorem-ipsum)
#+end_src

***** VUE

Have to add Vue to the Eglot ~eglot-server-programs~ [[https://emacs-lsp.github.io/lsp-mode/page/lsp-volar/][Vue 3 - LSP Mode - LSP support for Emacs]]

Only compatible with Emacs 30
#+begin_src emacs-lisp
(use-package vue-ts-mode
  :disabled
  :mode "\\.vue\\'")
  #+end_src

***** SVELTE

#+begin_src emacs-lisp
(use-package svelte-ts-mode
    :disabled
    :ensure nil
    :hook eglot-ensure)
#+end_src

#+begin_src emacs-lisp
(use-package svelte-mode
    :hook eglot-ensure)
#+end_src

***** GLSL

#+begin_src emacs-lisp
(use-package glsl-mode)
#+end_src

**** YAML
[[https://github.com/zkry/yaml-pro][ zkry/yaml-pro]]
[[https://blog.chmouel.com/2016/09/07/dealing-with-yaml-in-emacs/][The best ways to work with yaml files in Emacs | Chmouel's blog]]
[[https://emacs-lsp.github.io/lsp-mode/page/lsp-yaml/][YAML - LSP Mode - LSP support for Emacs]]

#+begin_src emacs-lisp
(use-package yaml-pro)

(use-package yaml
  :ensure nil
  :after yaml-pro
  :mode ("\\.yaml\\'" . yaml-ts-mode)
  :hook
  (yaml-ts-mode . yaml-pro-mode)
  (yaml-ts-mode . eglot-ensure))
#+end_src

**** JSON

Upgrade to using the tree-sitter package for syntax highlighting and enable lsp mode for JSON.

#+begin_src emacs-lisp
(use-package json
  :ensure nil
  :init
  (push '(js-json-mode . json-ts-mode) major-mode-remap-alist)
  :hook
  (json-ts . eglot-ensure))
#+end_src

Some packages to investigate
[[https://github.com/Sterlingg/json-snatcher][GitHub - Sterlingg/json-snatcher: Get the path to a JSON element in Emacs.]]
[[https://github.com/DamienCassou/json-navigator/tree/master][GitHub - DamienCassou/json-navigator: View and navigate JSON structures]]

***** JSON PRETTY DWIM

#+begin_quote
JSON JSON everywhere and I can't read a thing
#+end_quote

JSON in Emacs is constantly printed in a flat structure that makes me want to turn away and train to become a baker. This is some DWIM advice to print that JSON in a way that I can at least begin to grok... these are the ways in which I extend my life as a programmer.

#+begin_src emacs-lisp
(use-package json-pretty-dwim+
  :ensure nil
  :no-require
  :config
  (defun json-pretty-print-next+ ()
    (search-forward "{" nil t)
    (let ((start-point (goto-char (- (point) 1))))
      (json-read)
      (json-pretty-print start-point (point))))

  (defun json-pretty-print-buffer+ ()
    (goto-char (point-min))
    (while (not (eobp))
      (json-pretty-print-next+)))

  (defun json-pretty-print-dwim+ (orig-fun &rest args)
    ;; This function needs to be interactive in order for this advise to work when called interactively ie with `M-x'
    (interactive)
    (let ((inhibit-read-only buffer-read-only)
          (target-buffer-p (string=
                            (symbol-name 'json-pretty-print-buffer)
                            (subr-name orig-fun))))
      (condition-case nil
          (apply orig-fun args)
        (error
         (save-mark-and-excursion
           (if target-buffer-p
               (json-pretty-print-buffer+)
             (json-pretty-print-next+)))))
      (when buffer-read-only
        (set-buffer-modified-p nil))
      (read-only-mode buffer-read-only)))

  (advice-add 'json-pretty-print :around #'json-pretty-print-dwim+)

  (advice-add 'json-pretty-print-buffer :around #'json-pretty-print-dwim+))
#+end_src

***** JSON SCHEMAS

The [[https://github.com/microsoft/vscode/tree/main/extensions/json-language-features/server#settings][schemas]] setting for the [[https://github.com/microsoft/vscode][json-language-server]] should work when passed as ~:initializationOptions~ but it is failing... why?

The why is because the schemas should not be sent as part of the ~:initializationOptions~ but as a ~workspace/didChangeConfiguration~ notification.

The symbol for the JSON language server is unsurprisingly ~:json~.

#+begin_src emacs-lisp
(use-package eglot-json-schemas-extension
  :no-require
  :ensure nil
  :config
  ;; A list of the JSON schemas that I use cribbed from
  ;; https://github.com/emacs-lsp/lsp-mode/issues/3368#issuecomment-1050700910
  (defvar eglot-json--schema-associations+
    '((["package.json"] . "http://json.schemastore.org/package")
      (["tsconfig.json" "tsconfig.*.json"] . "http://json.schemastore.org/tsconfig")
      ([".eslintrc" ".eslintrc.json"] . "http://json.schemastore.org/eslintrc")
      (["manifest.json"] . "https://json.schemastore.org/chrome-manifest"))
    "Default json schemas.")

  (defun eglot-json--create-schema-associations+ ()
    "Transforms the json schemas in `eglot-json--schema-associations+' into the correct format for the lsp server."
    (cl-map
     'vector
     (lambda (item) (list :fileMatch (car item) :url (cdr item)))
     eglot-json--schema-associations+))

  (setq-default eglot-workspace-configuration
                (append eglot-workspace-configuration
                        `(:json
                          (:schemas
                           ,(eglot-json--create-schema-associations+))))))
#+end_src

**** CSV

#+begin_src emacs-lisp
(use-package csv-mode)
#+end_src

**** PYTHON

#+begin_src emacs-lisp
(use-package lsp-pyright
    :disabled
  :init
  (push '(python-mode . python-ts-mode) major-mode-remap-alist)
  :hook (python-ts-mode . (lambda ()
                            (require 'lsp-pyright)
                            (eglot-ensure))))
#+end_src

**** RACKET :: SICP

Really want to read Sicp at some point in my like... Maybe this will tempt me 🤞

#+begin_src emacs-lisp
(use-package racket-mode
  :disabled)
#+end_src

Org racket integration I am building this package via Nix so use-package complains about it not being found so to silence that wrong error message set `:ensure nil`
#+begin_src emacs-lisp
(use-package ob-racket
  :disabled
  :config
  (org-babel-do-load-languages 'org-babel-load-languages
                               (append org-babel-load-languages
                                       '((racket . t)))))
#+end_src

Download the SICP book in Info form
#+begin_src emacs-lisp
(use-package sicp
  :disabled)
#+end_src

**** DOCKER

#+begin_src emacs-lisp
(use-package dockerfile-ts-mode
  :ensure nil
  :mode "Dockerfile\\'" "\\.dockerfile\\'"
  :hook
  (dockerfile-ts-mode . eglot-ensure))
#+end_src

Broken on 
#+begin_src emacs-lisp
;; (use-package docker                     
;;   :bind
;;   ("C-c d" . docker))
#+end_src

**** PHP

This is a package that is built on the latest versions of tree-sitter https://github.com/emacs-php/php-ts-mode.
#+begin_src emacs-lisp
(use-package php-mode)
#+end_src

**** JENKINS

#+begin_src emacs-lisp
(use-package jenkinsfile-mode)
#+end_src

**** SQL

#+begin_src emacs-lisp
(use-package sql
      :ensure nil
    :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((sql . t)))))
#+end_src

#+begin_src emacs-lisp
(require 'vtable)
#+end_src

